<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @return Query
     */
    public function getAllQuery()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM AppBundle:Post as p')
            ;
        // todo Katya add method that will return query for request all posts
    }
}
